version: '3'

services:

  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: esquenta-imersao-fullcycle-next_test
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app